max_length_name: 50
max_length_email: 255
min_length_pwd: 6
size_avatar: 80
users:
  index:
    size_avatar_sm: 50
  per_page: 5
  expire_time_reset_pass: 2
  size_avatar_follow: 30
microposts:
  max_size_content: 140
  max_size_img: 5
  resize_img: [500, 500]
  format_type_img: ["image/jpeg", "image/gif", "image/png"]
